homepage/urls.py
from django.urls import path
from .views import index

urlpatterns = [
    path('', index , name='homepage'),
]

lilo/urls.py
from django.urls import path
from . import views

app_name = "lilo"

urlpatterns = [
    path('SignIn/', views.SignIn, name='SignIn'),
    path('SignOut/', views.SignOut, name='SignOut')
]

story6/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('story7/', include('story7.urls')),
    path('story8/', include('story8real.urls')),
    path('lilo/', include('lilo.urls')),
    

]

story7/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index , name='akordiong'),
]

story8real/urls.py
from django.urls import path
from . import views

app_name = 'books'

urlpatterns = [
    path('', views.books, name='books'),
    path('volumes/',views.search, name='search')
]

homepage/models.py
from django.db import models

# Create your models here.
class coreDatabase(models.Model):
    kabarUser = models.CharField(blank = False, max_length = 300, default='Gaada Kabar')
    waktu = models.DateTimeField(auto_now_add=True, null = True)

lilo/models.py
from django.db import models

# Create your models here.

story7/models.py
from django.db import models

# Create your models here.

story8real/models.py
from django.db import models

# Create your models here.

homepage/forms.py
from django import forms

class formKabar(forms.Form):
    Kabar = forms.CharField(widget = forms.TextInput(attrs={
        'class' : 'form-control',
        'placeholder' : 'kabar anda sedang gimana',
        'type' : 'text',
        'required' : True,
        'maxlength' : 300
    }))

homepage/views.py
from django.shortcuts import render, redirect
from . import forms, models

# Create your views here.
def index(request):
    if(request.method == "POST"):
        tmp = forms.formKabar(request.POST)
        if(tmp.is_valid()):
            tmp2 = models.coreDatabase()
            tmp2.kabarUser = tmp.cleaned_data["Kabar"]
            tmp2.save()
        return redirect("/")
    else:
        tmp = forms.formKabar()
        tmp2 = models.coreDatabase.objects.all()
        tmp_dictio = {
            'formKabar' : tmp,
            'coreDatabase' : tmp2
        }
        return render(request, 'homepage/homepage.html', tmp_dictio)

lilo/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.contrib.auth import authenticate, login as auth_SignIn, logout as auth_SignOut

def SignIn(request):
    if request.user.is_authenticated:
        return redirect('books:books')
    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                auth_SignIn(request, user)
                request.session['username'] = user.first_name
                return redirect('books:books')
            else:
                return render(request, 'SignIn.html', {
                        'error' : 'invalid username or password'
                    }
                )
    return render(request, 'SignIn.html')

def SignOut(request):
    auth_SignOut(request)
    return redirect('books:books')

story7/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, "akordiong.html")

story8real/views.py
from django.http import HttpResponseForbidden, JsonResponse
from django.shortcuts import render
import json
import requests


def books(request):
    return render(request, 'ayax.html')

def search(request):
    url = 'https://www.googleapis.com/books/v1/volumes'
    url +=  f"?maxResults={10}&q={request.GET.get('q')}"
    data = requests.get(url).json()
    return JsonResponse(data, json_dumps_params={'indent': 2})

homepage/templates/homepage/homepage.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'css/kabar.css' %}" />
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    <link
      href="https://fonts.googleapis.com/css?family=Italianno|Montserrat:400,700|Raleway:400,700&display=swap"
      rel="stylesheet"
    />
    <title>Story6</title>
  </head>

  <body style="background-color: bisque;">
    <div class="container">
      <div class="kabar">
        <div
          class="judulkabar d-flex justify-content-center"
          style="background-color: aquamarine;"
        >
          <p>
            <b name="judul">Halo, apa kabar?</b>
          </p>
        </div>
        <div class="kabar2" style="background-color: aqua;">
          <form action="" method="POST">
            {% csrf_token %} {{ formKabar }}
            <div class="centre-items text-right" style="margin-top: 2%">
              <input type="submit" class="btn btn-success" value="masukan" />
            </div>
          </form>
        </div>
        <div
          class="table-responsive"
          id="Table"
          style="background-color: aqua;"
        >
          <table class="table table-hover">
            <thead>
              <tr class="d-flex" style="background-color: aquamarine;">
                <th scope="col" class="col-4">Waktu</th>
                <th scope="col" class="col-8">Cerita</th>
              </tr>
            </thead>
            {% for i in coreDatabase %}
            <tbody>
              <tr class="d-flex">
                <td class="col-4">{{ i.waktu }}</td>
                <td class="col-8">{{ i.kabarUser }}</td>
              </tr>
            </tbody>
            {% endfor %}
          </table>
        </div>
      </div>
    </div>
  </body>
</html>

lilo/templates/SignIn.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Login Page</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/story8.css' %}" />
    <script
      type="text/Javascript"
      src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    ></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </head>
  {% block content %}
  <div class="SignIn">
    <div class="container h-100">
      <div class="d-flex justify-content-center h-100">
        <div class="user_card">
          <div class="d-flex justify-content-center">
            <div class="brand_logo_container">
              <img
                src="{% static 'assets/hoi.jpg' %}"
                class="brand_logo"
                alt="Logo"
              />
            </div>
          </div>
          <div class="d-flex justify-content-center form_container">
            <form method="POST">
              {% csrf_token %}
              <div class="input-group mb-3">
                <input
                  type="text"
                  name="username"
                  class="form-control input_user"
                  value=""
                  placeholder="username"
                />
              </div>
              <div class="input-group mb-2">
                <input
                  type="password"
                  name="password"
                  class="form-control input_pass"
                  value=""
                  placeholder="password"
                />
              </div>
              <div class="d-flex justify-content-center mt-3 login_container">
                <button type="submit" name="button" class="btn login_btn">
                  Sign In
                </button>
              </div>
            </form>
          </div>
          {% if error %}
          <div class="alert alert-warning alert-dismissible fade show">
            <strong>Warning!</strong> {{ error }}
          </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>

  {% endblock content %}
</html>

story7/templates/akordiong.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'kabar.css' %}" />

    <title>Story 7</title>
  </head>
  <body id="body" class="dark-mode">
    <div class="container">
      <div class="basa basi">
        <div class="row">
          <h2>Hai, Apakabar? lagi</h2>
          <p>
            nama saya muhammad ramy azhar, mahasiswa fasilkom ui angaktan 2018,
            hobi saya membaca buku nah dibawah ini ada beberapa list aktifitas
            saya, organisasi/kepanitiaan yang saya ikuti, dan prestasi yang
            pernah saya raih. oiya ketiganya bisa di klik lhoo.. kalian coba
            dehh.. dan halaman ini bisa berubah temanya... coba kamu klik tombol
            dipaling bawah yang tulisannya "ganti tema".
          </p>
        </div>
      </div>
      <div class="row">
        <button class="accordion">Aktifitas</button>
        <div class="panel">
          <p>
            Makan
          </p>
          <p>Tidur</p>
          <p>Solat</p>
          <p>Ngoding</p>
          <p>Dota</p>
        </div>

        <button class="accordion">Organisasi / kepanitian</button>
        <div class="panel">
          <p>
            Bem
          </p>
          <p>Openhouse Fasilkom UI</p>
          <p>Compfest</p>
        </div>

        <button class="accordion">Prestasi</button>
        <div class="panel">
          <p>
            Juara 1 Lomba Balap sepeda
          </p>
          <p>Juara harapan 3 Lomba catur</p>
          <p>Juara Favorit Lomba masak</p>
        </div>
      </div>
      <button
        type="button"
        class="btn btn-success"
        name="dark_light"
        onclick="toggleDarkLight()"
      >
        Ganti tema
      </button>
    </div>

    <script>
      var acc = document.getElementsByClassName("accordion");
      var i;

      for (i = 0; i < acc.length; i++) {
        acc[i].addEventListener("click", function() {
          this.classList.toggle("active");
          var panel = this.nextElementSibling;
          if (panel.style.display === "block") {
            panel.style.display = "none";
          } else {
            panel.style.display = "block";
          }
        });
      }
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script
      src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
      integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
      crossorigin="anonymous"
    ></script>
    <script src="{% static 'js.js' %}"></script>
  </body>
</html>

story8real/templates/ayax.html
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>My Favourite Book</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    />
    <link rel="stylesheet" href="{% static 'css/story8.css' %}" />
    <script
      type="text/Javascript"
      src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"
    ></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  </head>
  {% block content %}
  <div class="allcontent">
    <form method="GET" class="form" action="volumes">
      {% csrf_token %}
      <div class="form-group">
        {% if user.is_authenticated %}
        <label for="status" class="labelsearch"
          >Hey {{ request.user.username }}, do you wanna search some
          books?</label
        >
        {% else %}
        <label for="status" class="labelsearch"
          >Hey Anonymous, do you wanna search some books? login dulu
          please</label
        >
        {% endif %}
        <input
          type="text"
          class="form-control"
          id="searchfield"
          placeholder="search your books"
          name="searchfield"
        />
      </div>

      {% if user.is_authenticated %}
      <button type="submit" class="btn btn-primary" id="submit">Search</button>
      <a
        class="btn btn-danger"
        href="{% url 'lilo:SignOut' %}"
        id="text-nav-oauth"
        >Sign Out</a
      >
      {% else %}
      <a
        class="btn btn-success"
        href="{% url 'lilo:SignIn' %}"
        id="text-nav-oauth"
        >Sign In</a
      >
      {% endif %}
      <div id="log-button"></div>
    </form>
  </div>

  <div class="container mt-5">
    <h1 class="keyword-results">Results</h1>
  </div>

  <div id="book-results-table" class="table-responsive">
    <div class="container mt-5">
      <table class="table">
        <thead class="thead-light">
          <tr>
            <th class="align-middle" scope="col">No.</th>
            <th class="align-middle" scope="col">Book Information</th>
            <th class="align-middle" scope="col">Cover</th>
          </tr>
        </thead>
        <tbody id="results"></tbody>
      </table>
    </div>
  </div>
  {% endblock content %} {% block custom_scripts %}
  <script src="{% static 'js/story8.js' %}"></script>
  {% endblock custom_scripts %}
</html>

templates/base.html
{% load static %}
<html>
  <head>
    <title>{% block title %}{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <!-- add icon -->
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />

    <!-- connect css with bootstrap -->
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
      crossorigin="anonymous"
    />
    <link rel="Stylesheet" href="{% static 'css/status.css' %}" />

    <!-- use proper font -->
    <link
      href="https://fonts.googleapis.com/css?family=Racing+Sans+One&display=swap"
      rel="stylesheet"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Nunito&display=swap"
      rel="stylesheet"
    />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <script src="{% static 'js/status.js' %}"></script>
  </head>

  <body>
    <div id="navbarcolor">
      <nav class="navbar navbar-expand-sm navbar-dark">
        <!-- Brand -->
        <a class="navbar-brand" href="#"
          ><img src="{% static 'assets/title.png' %}" width="20" height="20"
        /></a>

        <!-- Links -->
        <ul class="navbar-nav">
          <li class="nav-item">
            <a
              class="nav-link"
              href="{% url 'status:status' %}"
              id="text-nav-status"
              >Status</a
            >
          </li>
          <li class="nav-item">
            <a
              class="nav-link"
              href="{% url 'about:about' %}"
              id="text-nav-about"
              >About</a
            >
          </li>
          <li class="nav-item">
            <a
              class="nav-link"
              href="{% url 'books:books' %}"
              id="text-nav-books"
              >Books</a
            >
          </li>

          <!-- Dropdown -->
          <li class="nav-item dropdown">
            <a
              id="text-nav-theme"
              class="nav-link dropdown-toggle"
              href="#"
              id="navbardrop"
              data-toggle="dropdown"
            >
              Change Theme
            </a>
            <div class="dropdown-menu">
              <a class="dropdown-item" onclick="changeThemeGreen()">Green</a>
              <a class="dropdown-item" onclick="changeThemeMonochrome()"
                >Monochrome</a
              >
            </div>
          </li>
          <div id="log-button" class="nav-item mx-2 my-2 my-md-0">
            {% if user.is_authenticated %}
            <a
              class="btn btn-primary"
              href="{% url 'authentication:SignOut' %}"
              id="text-nav-oauth"
              >Sign Out</a
            >
            {% else %}
            <a
              class="btn btn-primary"
              href="{% url 'authentication:SignIn' %}"
              id="text-nav-oauth"
              >Sign In</a
            >
            {% endif %}
          </div>
        </ul>
      </nav>
    </div>

    {% block content %} {% endblock %} {% block custom_scripts %} {% endblock
    custom_scripts %}
  </body>
</html>